# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14178d1ad9ba77ca6af6f4a6c6de9f13d9a8b9e4fb1c062d705b383eaa65c5dc59f35e527ecd609767f44a2cc89b302d4a8127a6a34846608bf35544a8e2926c

test:
  secret_key_base: 3481af46d186b8a78a7384806080dd801417c8319396160df8690fb21a415328870a6e38679339faa62ae5223f6ca200fd6cb388a19688fe1ba13f19643506aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
